name: Setup Node.js
description: Setup Node.js

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      name: Setup Node.js
      with:
        node-version-file: .nvmrc
    - name: Install dependencies
      run: npm i
      shell: bash
